// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQsJ_vlhx1V5v1a6nG79cq1r1KLMTYuis',
    appId: '1:714461113144:web:a5b8a1a0ebeb3fec212fcd',
    messagingSenderId: '714461113144',
    projectId: 'marketbase-e1978',
    authDomain: 'marketbase-e1978.firebaseapp.com',
    storageBucket: 'marketbase-e1978.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIDy5gfQLA1E2WFqhkZ2zxfyEWLJaKNXo',
    appId: '1:714461113144:android:096cdb4e141e1cab212fcd',
    messagingSenderId: '714461113144',
    projectId: 'marketbase-e1978',
    storageBucket: 'marketbase-e1978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt2DKD8f8fuKGnNze0AAHwdpfOuNqJ7Vw',
    appId: '1:714461113144:ios:2a0545d2dcb8c7c6212fcd',
    messagingSenderId: '714461113144',
    projectId: 'marketbase-e1978',
    storageBucket: 'marketbase-e1978.appspot.com',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt2DKD8f8fuKGnNze0AAHwdpfOuNqJ7Vw',
    appId: '1:714461113144:ios:2a0545d2dcb8c7c6212fcd',
    messagingSenderId: '714461113144',
    projectId: 'marketbase-e1978',
    storageBucket: 'marketbase-e1978.appspot.com',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQsJ_vlhx1V5v1a6nG79cq1r1KLMTYuis',
    appId: '1:714461113144:web:dc72733f5e2bfe75212fcd',
    messagingSenderId: '714461113144',
    projectId: 'marketbase-e1978',
    authDomain: 'marketbase-e1978.firebaseapp.com',
    storageBucket: 'marketbase-e1978.appspot.com',
  );
}
